### ISSUE TITLE
Some sort of java type related crash

### ISSUE THREAD

**Issue by ilazarte** [Artur-Brahms/Bitwig-MidiFighterTwister-CME#2] opened 2021-01-30 21:34 UTC
https://imgur.com/a/G0SdJ5B 

Not sure how much you can do about this, seems like it might be internal to Bitwig (sigh).  I was mapping a traktor knob to my twister with latest firmware.

**Comment by ilazarte** [comment] 2021-01-30 21:45
I just tried against the latest (0.5.5) and it seems to be working... crossing fingers.

**Comment by Artur-Brahms** [comment] 2021-01-30 22:10
It was a known bug caused by the changes in Bitwig v3.3 and should be fixed in v0.5.5.

**Closed as completed by Artur-Brahms** 2021-01-30 22:10 UTC
